spring:
  redis:
    host: 47.112.162.182  # Redis 服务器地址  127.0.0.1
    port: 6379       # Redis 端口号
    password: redis000000.        # Redis 密码（如果没有密码则留空）
    database: 0      # 数据库索引（默认0）
    timeout: 3000ms  # 连接超时时间
#    lettuce:         # 如果使用 Lettuce 客户端
#      pool:
#        max-active: 8   # 最大连接数
#        max-idle: 8     # 最大空闲连接
#        min-idle: 2     # 最小空闲连接
#        max-wait: -1ms  # 最大等待时间（-1表示无限制）