# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    threads:
      # 最少线程数
      min-spare: 10
      # 最多线程数
      max: 20
    # 最大连接数
    max-connections: 30
    # 最大等待数
    accept-count: 10

# spring相关配置
spring:
  profiles:
    active: dev

# log 配置
logging:
  level:
    root: info
    com.noob.base: debug # com.noob.base 目录下为debug级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M:%L - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
